INSERT INTO CASELOADS (CASELOAD_ID, DESCRIPTION, CASELOAD_TYPE) VALUES ('NWEB', 'Magic API NomisCaseload', 'APP');
INSERT INTO CASELOADS (CASELOAD_ID, DESCRIPTION, CASELOAD_TYPE) VALUES ('MDI', 'Moorlands', 'INST');
INSERT INTO CASELOADS (CASELOAD_ID, DESCRIPTION, CASELOAD_TYPE) VALUES ('BXI', 'Brixton', 'INST');
INSERT INTO CASELOADS (CASELOAD_ID, DESCRIPTION, CASELOAD_TYPE) VALUES ('LEI', 'Leeds', 'INST');
INSERT INTO CASELOADS (CASELOAD_ID, DESCRIPTION, CASELOAD_TYPE) VALUES ('WAI', 'Waylands', 'INST');
INSERT INTO CASELOADS (CASELOAD_ID, DESCRIPTION, CASELOAD_TYPE) VALUES ('ZZGHI', 'Ghost NomisCaseload', 'INST');
INSERT INTO CASELOADS (CASELOAD_ID, DESCRIPTION, CASELOAD_TYPE) VALUES ('CADM', 'Central Admin', 'ADMIN');
