INSERT INTO ADDRESS_USAGES(ADDRESS_ID, ADDRESS_USAGE) VALUES (-1,'HOME')
INSERT INTO ADDRESS_USAGES(ADDRESS_ID, ADDRESS_USAGE) VALUES (-2,'RELLIES')
INSERT INTO ADDRESS_USAGES(ADDRESS_ID, ADDRESS_USAGE) VALUES (-3,'GRANNY')
INSERT INTO ADDRESS_USAGES(ADDRESS_ID, ADDRESS_USAGE) VALUES (-4,'REFUGE')
INSERT INTO ADDRESS_USAGES(ADDRESS_ID, ADDRESS_USAGE) VALUES (-5,'HOSTEL')

INSERT INTO ADDRESS_USAGES (ADDRESS_ID, ADDRESS_USAGE, ACTIVE_FLAG, CREATE_DATETIME, CREATE_USER_ID) VALUES (121010,    'RECEP', 'Y', '2018-03-08T12:21:23.967Z', 'XTAG')
INSERT INTO ADDRESS_USAGES (ADDRESS_ID, ADDRESS_USAGE, ACTIVE_FLAG, CREATE_DATETIME, CREATE_USER_ID) VALUES (121010,    'RELEASE','Y', '2018-03-08T12:21:23.973Z', 'XTAG')
