INSERT INTO MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE, DESCRIPTION, LIST_SEQ) VALUES ('REL', 'DD', 'Movement 1', 1);

INSERT INTO MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE, DESCRIPTION, LIST_SEQ) VALUES ('TRN', 'NOTR', 'description',1 );
INSERT INTO MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE, DESCRIPTION, LIST_SEQ) VALUES ('TRN', 'MOTR', 'description',1 );
INSERT INTO MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE, DESCRIPTION, LIST_SEQ) VALUES ('CRT', 'CRT', 'description',1 );
INSERT INTO MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE, DESCRIPTION, LIST_SEQ) VALUES ('TAP', 'C3', 'description',1 );
INSERT INTO MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE, DESCRIPTION, LIST_SEQ) VALUES ('TAP', 'C6', 'description',1 );
INSERT INTO MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE, DESCRIPTION, LIST_SEQ) VALUES ('ADM', 'N', 'description',1 );
INSERT INTO MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE, DESCRIPTION, LIST_SEQ) VALUES ('ADM', 'I', 'description',1 );
INSERT INTO MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE, DESCRIPTION, LIST_SEQ) VALUES ('REL', 'UAL', 'description',1 );
INSERT INTO MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE, DESCRIPTION, LIST_SEQ) VALUES ('REL', 'UAL_ECL', 'description',1);
INSERT INTO MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE, DESCRIPTION, LIST_SEQ) VALUES ('REL', 'ESCP', 'description',1);
INSERT INTO MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE, DESCRIPTION, LIST_SEQ) VALUES ('ADM', 'RECA', 'description',1);
INSERT INTO MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE, DESCRIPTION, LIST_SEQ) VALUES ('ADM', 'INT', 'description',1);