# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: quay.io/hmpps/custody-api
  tag: latest
  pullPolicy: Always
  port: 8080
